Convert weight desct to format any for conv/deconv backward
intel/ideep pull request #291
Opened 2024-03-14 07:49 UTC by Xia-Weiwen

## Description
This is a bug fix. Weight desc format should be `any` to query primitive desc. But in the following two cases, weight desc format is set to plain by mistake:
- Convolution backward_data when group > 1
- Deconvolution backward_weights when group > 1

This PR fixes the issue by converting weight desct to format any in such cases.

## Test results
### Convolution with group > 1 backward_data
**test code:**
```python
import torch
m = torch.nn.Conv2d(in_channels=960, out_channels=960, kernel_size=3, stride=1, padding=1, groups=960)
input = torch.randn(96, 960, 7, 7, requires_grad=True)
m.to(memory_format=torch.channels_last)
input.to(memory_format=torch.channels_last)
if use_bf16:
    m = m.to(torch.bfloat16)
    input = input.to(torch.bfloat16)
output = m(input)
loss = output.mean()
loss.backward()
```
**before**
FP32
onednn_verbose,primitive,exec,cpu,convolution,**ref:any**,backward_data,src_f32::blocked:acdb::f0 wei_f32::blocked:abcde::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g960mb96_ic960oc960_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,**40.8711**
BF16
onednn_verbose,primitive,exec,cpu,convolution,**ref:any**,backward_data,src_bf16::blocked:acdb::f0 wei_bf16::blocked:abcde::f0 bia_undef::undef::: dst_bf16::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g960mb96_ic960oc960_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,**68.365**

**after**
FP32
onednn_verbose,primitive,exec,cpu,convolution,**jit_dw:avx512_core**,backward_data,src_f32::blocked:acdb::f0 wei_f32:a:blocked:Abcde16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g960mb96_ic960oc960_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,**0.610107**

BF16
onednn_verbose,primitive,exec,cpu,convolution,**jit_dw:avx512_core_bf16**,backward_data,src_bf16::blocked:acdb::f0 wei_bf16:a:blocked:Abcde16a::f0 bia_undef::undef::: dst_bf16::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g960mb96_ic960oc960_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,**0.689941**

### Deconvolution with group > 1 backward_weights
**test code:**
```python
import torch
m = torch.nn.ConvTranspose2d(in_channels=960, out_channels=960, kernel_size=3, stride=1, padding=1, groups=960)
input = torch.randn(96, 960, 7, 7, requires_grad=True)
m.to(memory_format=torch.channels_last)
input.to(memory_format=torch.channels_last)
if use_bf16:
    m = m.to(torch.bfloat16)
    input = input.to(torch.bfloat16)
output = m(input)
loss = output.mean()
loss.backward()
```
**before**
FP32
onednn_verbose,primitive,exec,cpu,deconvolution,**conv:any+ref:any**,backward_weights,src_f32::blocked:acdb::f0 wei_f32::blocked:abcde::f0 bia_f32:a:blocked:a::f0 dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:deconvolution_direct,g960mb96_ic960oc960_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,**3.62012**

BF16
onednn_verbose,primitive,exec,cpu,deconvolution,**conv:any+ref:any**,backward_weights,src_bf16::blocked:acdb::f0 wei_bf16::blocked:abcde::f0 bia_bf16:a:blocked:a::f0 dst_bf16::blocked:acdb::f0,attr-scratchpad:user ,alg:deconvolution_direct,g960mb96_ic960oc960_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,**7.23511**

**after**
FP32
onednn_verbose,primitive,exec,cpu,deconvolution,**conv:any+jit_dw:avx512_core**,backward_weights,src_f32::blocked:acdb::f0 wei_f32:a:blocked:Abcde16a::f0 bia_f32:a:blocked:a::f0 dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:deconvolution_direct,g960mb96_ic960oc960_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,**0.391113**
BF16
onednn_verbose,primitive,exec,cpu,deconvolution,**conv:any+jit_dw:avx512_core_bf16**,backward_weights,src_bf16::blocked:acdb::f0 wei_bf16:a:blocked:Abcde16a::f0 bia_bf16:a:blocked:a::f0 dst_bf16::blocked:acdb::f0,attr-scratchpad:user ,alg:deconvolution_direct,g960mb96_ic960oc960_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,**0.580078**

---
@jgong5 @yanbing-j Please review. Thanks.

2024-03-14 13:27 UTC, jgong5 requested changes
Is it better to fix `to_grouped` function implementation instead? The format any should be preserved in it?

2024-03-15 00:48 UTC, Xia-Weiwen commented
> Is it better to fix `to_grouped` function implementation instead? The format any should be preserved in it?

Hi @jgong5. Thanks for your review. Unfortunately, the original format tag cannot be obtained due to limitation of oneDNN `memory::desc` API, so we don't know the original format. Then it leaves to the caller to preserve the format. This is also done in other cases, such as conv/deconv forward and conv backward_weights. The cases in this PR had been missed before.

2024-03-15 00:59 UTC, jgong5 commented
> > Is it better to fix `to_grouped` function implementation instead? The format any should be preserved in it?
> 
> Hi @jgong5. Thanks for your review. Unfortunately, the original format tag cannot be obtained due to limitation of oneDNN `memory::desc` API, so we don't know the original format. Then it leaves to the caller to preserve the format. This is also done in other cases, such as conv/deconv forward and conv backward_weights. The cases in this PR had been missed before.

I saw `get_format_kind` method of memory descriptor. It is not usable?

2024-03-15 01:17 UTC, Xia-Weiwen commented
> I saw `get_format_kind` method of memory descriptor. It is not usable?

The `get_format_kind` returns the following enum class:
```c++
    /// Memory format kind
    enum class format_kind {
        /// Undefined memory format kind, used for empty memory descriptors.
        undef = dnnl_format_kind_undef,
        /// A special format kind that indicates that the actual format will be
        /// selected by a primitive automatically.
        any = dnnl_format_kind_any,
        /// A tensor in a generic format described by the stride and blocking
        /// values in each dimension.
        blocked = dnnl_blocked,
#ifdef DNNL_EXPERIMENTAL_SPARSE
        /// Format kind for sparse tensors.
        sparse = dnnl_format_kind_sparse,
#endif
        /// A special format kind that indicates that tensor format is opaque.
        opaque = dnnl_format_kind_opaque,
    };
```
It does not return the actual format tag. We can get `any` but no other specific format tags. So, we cannot preserve the format tag in most cases in `to_grouped`.

2024-03-15 03:50 UTC, jgong5 commented
> It does not return the actual format tag. We can get `any` but no other specific format tags. So, we cannot preserve the format tag in most cases in `to_grouped`.

We only need to take care of `any` but not other formats here, right?

2024-03-15 03:55 UTC, Xia-Weiwen commented
> > It does not return the actual format tag. We can get `any` but no other specific format tags. So, we cannot preserve the format tag in most cases in `to_grouped`.
> 
> We only need to take care of `any` but not other formats here, right?

In this case, yes. But if we want `to_grouped` to preserve format, I think it has to work in all cases not just for `any`, right?

2024-03-15 04:04 UTC, jgong5 commented
> > > It does not return the actual format tag. We can get `any` but no other specific format tags. So, we cannot preserve the format tag in most cases in `to_grouped`.
> > 
> > 
> > We only need to take care of `any` but not other formats here, right?
> 
> In this case, yes. But if we want `to_grouped` to preserve format, I think it has to work in all cases not just for `any`, right?

I don't think it makes sense to ask `to_grouped` to keep format right? The format with groups would be different if it is specified. But preserving `any` does make sense?

2024-03-15 04:37 UTC, Xia-Weiwen commented
> > In this case, yes. But if we want `to_grouped` to preserve format, I think it has to work in all cases not just for `any`, right?
> 
> I don't think it makes sense to ask `to_grouped` to keep format right? The format with groups would be different if it is specified. But preserving `any` does make sense?

Did you mean that inside `to_grouped`, we preserve `any` for `any` and return plain format for other formats?

2024-03-15 05:29 UTC, jgong5 commented
> > > In this case, yes. But if we want `to_grouped` to preserve format, I think it has to work in all cases not just for `any`, right?
> > 
> > 
> > I don't think it makes sense to ask `to_grouped` to keep format right? The format with groups would be different if it is specified. But preserving `any` does make sense?
> 
> Did you mean that inside `to_grouped`, we preserve `any` for `any` and return plain format for other formats?

Yes.

2024-03-15 07:55 UTC, Xia-Weiwen commented
> > > > In this case, yes. But if we want `to_grouped` to preserve format, I think it has to work in all cases not just for `any`, right?
> > > 
> > > 
> > > I don't think it makes sense to ask `to_grouped` to keep format right? The format with groups would be different if it is specified. But preserving `any` does make sense?
> > 
> > 
> > Did you mean that inside `to_grouped`, we preserve `any` for `any` and return plain format for other formats?
> 
> Yes.

Ok. Thanks. I have updated the PR to preserve format tag `any`.

2024-03-15 10:12 UTC, jgong5 approved these changes

2024-03-15 11:22 UTC, Xia-Weiwen commented
Hi @yanbing-j Could you please help merge this PR? Thanks.

2024-03-16 00:34 UTC, merged

2024-03-16 00:34 UTC, yanbing-j commented
Please port to other branches if needed. @Xia-Weiwen